common/models/NewsAttach.php
<?php

namespace common\models;

use yii\db\ActiveRecord;
use Yii;

class NewsAttach extends ActiveRecord
{
    const POS_SLIDER = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news_attach';
    }

    public function rules()
    {
        return [
            [['news_id', 'attachment'], 'required'],
            [['news_id', 'attachment'], 'integer'],
            [['news_id'], 'exist', 'skipOnError' => true, 'targetClass' => News::className(), 'targetAttribute' => ['news_id' => 'id']],
        ];
    }

    public function getNews()
    {
        return $this->hasOne(News::className(), ['id' => 'news_id']);
    }
}

backend/controllers/NewsAttachController.php
<?php

namespace backend\controllers;

use common\models\News;
use common\models\User;
use Yii;
use common\models\NewsAttach;
use common\models\NewsAttachSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsAttachController implements the CRUD actions for NewsAttach model.
 */
class NewsAttachController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($role, $action) {
                            $res = Yii::$app->user->identity->level >= User::LEVEL_EDITOR;
                            if (!$res) {
                                Yii::info(
                                    'Access violation: User [' . Yii::$app->user->identity->username . '] at ' . __CLASS__
                                    , 'security'
                                );
                            }

                            return $res;
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all NewsAttach models.
     * @return mixed
     */
    public function actionIndex()
    {
        $data = [];
        $data['slider'] = NewsAttach::find()->where(['attachment' => NewsAttach::POS_SLIDER])->all();

        return $this->render('index', $data);
    }

    /**
     * Displays a single NewsAttach model.
     * @param string $id
     * @param string $news_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new NewsAttach model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NewsAttach();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::info('[news-attach][create][' . $model->id . ']', 'userBehaviour');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'news' => News::getAllNews(),
            ]);
        }
    }

    /**
     * Updates an existing NewsAttach model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @param string $news_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::info('[news-attach][update][' . $model->id . ']', 'userBehaviour');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'news' => News::getAllNews(),
            ]);
        }
    }

    /**
     * Deletes an existing NewsAttach model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @param string $news_id
     * @return mixed
     */
    public function actionDelete($id, $news_id)
    {
        $model = $this->findModel($id, $news_id);
        Yii::info('[news-attach][delete][' . $model->id . ']', 'userBehaviour');
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the NewsAttach model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @param string $news_id
     * @return NewsAttach the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NewsAttach::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/news-attach/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\NewsAttach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-attach-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'attachment')->widget(\kartik\select2\Select2::classname(), [
        'name' => 'attachment',
        'value' => '',
        'data' => [
                \common\models\NewsAttach::POS_SLIDER => 'Slider',
        ],
        'options' => ['placeholder' => 'Wybierz pozycję']
    ]); ?>

    <?= $form->field($model, 'news_id')->widget(\kartik\select2\Select2::classname(), [
        'data' => $news,
        'language' => 'pl',
        'options' => ['placeholder' => 'Wybierz news'],
        'pluginOptions' => [
            'allowClear' => false,
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/news-attach/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\NewsAttachSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-attach-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'attachment') ?>

    <?= $form->field($model, 'news_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/news-attach/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\NewsAttach */

$this->title = 'Create News Attach';
$this->params['breadcrumbs'][] = ['label' => 'News Attaches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-attach-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'news' => $news
    ]) ?>

</div>

backend/views/news-attach/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\NewsAttachSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'News Attaches';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-attach-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p class="alert alert-info">
        Możesz tutaj przypiąć newsy na stałe w danych pozycjach. Będą miały pierwszeństwo przed tymi
        wyświetlanymi przez system.
    </p>

    <p><?= Html::a('Create News Attach', ['create'], ['class' => 'btn btn-success']) ?></p>

    <h2>Sekcje</h2>
    <h3>Slider</h3>
    <ul>
    <?php foreach ($slider as $d): ?>
        <li><a href="<?= \yii\helpers\Url::to(['news-attach/view', 'id' => $d->id]); ?>"><?= $d->news->title; ?></a></li>
    <?php endforeach; ?>
    </ul>
</div>

backend/views/news-attach/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\NewsAttach */

$this->title = 'Update News Attach: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'News Attaches', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id, 'news_id' => $model->news_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="news-attach-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'news' => $news,
    ]) ?>

</div>

backend/views/news-attach/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\NewsAttach */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'News Attaches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-attach-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id, 'news_id' => $model->news_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id, 'news_id' => $model->news_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'attachment',
            'news_id',
        ],
    ]) ?>

</div>