common/models/Comic.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the model class for table "comic".
 *
 * @property int $id
 * @property int $user_id
 * @property string $img
 * @property string $title
 * @property string $slug
 * @property int $date
 */
class Comic extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comic';
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'slugAttribute' => 'slug',
                'attribute' => 'title',
                'ensureUnique' => true,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['img', 'date', 'title'], 'required'],
            [['img', 'title'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'img' => 'Image',
            'title' => 'Title',
            'slug' => 'Slug',
            'date' => 'Date',
        ];
    }

    public function beforeSave($insert)
    {
        $this->date = Yii::$app->formatter->asTimestamp($this->date);
        return parent::beforeSave($insert);
    }

    public function afterFind()
    {
        $this->date = Yii::$app->formatter->asDate($this->date, 'dd.MM.y');
        if ($this->date == 0 || $this->date == null) {
            $this->date = null;
        } else {
            $this->date = Yii::$app->formatter->asDate($this->date, 'dd.MM.y');
        }
    }
}

backend/controllers/ComicController.php
<?php

namespace backend\controllers;

use common\models\User;
use Yii;
use common\models\Comic;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ComicController implements the CRUD actions for Comic model.
 */
class ComicController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Comic models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Comic::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comic model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comic();
        if ($model->user_id == null) {
            $model->user_id = Yii::$app->user->id;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::info('[comic][update][' . $model->id . '][' . $model->title . ']', 'userBehaviour');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        Yii::info('[comic][delete][' . $model->id . '][' . $model->title . ']', 'userBehaviour');
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Comic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comic::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ComicController.php
<?php

namespace frontend\controllers;

use common\models\Comic;
use frontend\components\FrontController;
use yii\data\Pagination;

class ComicController extends FrontController
{
    public function actionView($id, $slug = null)
    {
        $model = Comic::find()->where(['id' => $id])->one();
        if ($model == null) {
            return $this->goHome();
        }

        // if link without slug and slug exists in db (no infinite redirects)
        if ($slug == null && $model->slug != null) {
            return $this->redirect(['news', 'id' => $id, 'slug' => $model->slug]);
        }
        // if slugs doesnt match
        if ($slug != null && $model->slug != null) {
            if ($slug != $model->slug) {
                return $this->redirect(['news', 'id' => $id, 'slug' => $model->slug]);
            }
        }



        return $this->render('index', [
            'model' => $model,
            'next' => Comic::find()->where(['>', 'id', $id])->orderBy(['id' => SORT_ASC])->one(),
            'previous' => Comic::find()->where(['<', 'id', $id])->orderBy(['id' => SORT_DESC])->one(),
        ]);
    }

    public function actionList()
    {
        $query = Comic::find();
        $count = $query->count();
        $pagination = new Pagination(['totalCount' => $count, 'pageSize' => 16]);
        $models = $query
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('list', [
            'models' =>  $models,
            'pagination' => $pagination,
        ]);
    }
}

frontend/views/comic/index.php
<?php

/* @var $this yii\web\View */
use yii\web\View;

$this->title = $model->title . ' · GameLoad';

$this->registerJs("
$('.gallery').slick({
    centerMode: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    lazyLoad: 'progressive',
    variableWidth: true,
    focusOnSelect: true,
    arrows: false,
    dots: false, 
    responsive: [
        {
            breakpoint: 768,
            settings: {
                centerMode: false,
            }
        }
    ]
});", View::POS_READY);

$this->render('../layouts/facebookSdk.php');

?>
<div id="fb-root"></div>

<div class="news-content">
    <h1><?= $model->title ?></h1>
    <div class="news-h-separator"></div>

    <a href="<?= $model->img ?>">
        <img class="img-responsive" src="<?= $model->img ?>">
    </a>

    <div class="comic-buttons">
        <?php if ($previous !== null): ?>
        <a href="<?= \yii\helpers\Url::to(['comic/view', 'id' => $previous->id, 'slug' => $previous->slug]) ?>">
            <button class="big-button comic-button previous">Poprzedni</button>
        </a>
        <?php endif; ?>
        <?php if ($next !== null): ?>
        <a href="<?= \yii\helpers\Url::to(['comic/view', 'id' => $next->id, 'slug' => $next->slug]) ?>">
            <button class="big-button comic-button next">Następny</button>
        </a>
        <?php endif; ?>
    </div>
</div>
<div class="clearfix"></div>

<?= $this->render('../layouts/disqus.php', ['model' => $model]); ?>
<?= $this->render('../layouts/facebookSocial.php') ?>

frontend/views/comic/list.php
<?php

/* @var $this yii\web\View */
use yii\web\View;
use frontend\components\NewsTileWidget;

$this->title = Yii::$app->name . ' · Komiksy';
\frontend\assets\SlickAsset::register($this);
?>

<div class="padded-multiline">
    <h1 class="gradient-blue-heading">Komiksy</h1>
</div>

<?php if (count($models) <= 0): ?>
    <p class="no-content">
        Nie znaleziono żadnych wyników.
    </p>
<?php endif; ?>

<section class="row section-category">
    <?php foreach ($models as $s) echo NewsTileWidget::widget(['model' => $s, 'colSize' => 4, 'comic' => true]); ?>
</section>

<?= \yii\widgets\LinkPager::widget([
    'pagination' => $pagination,
]); ?>