backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use common\models\Category;
use common\models\NewsWithCategories;
use common\models\User;
use Yii;
use common\models\News;
use common\models\NewsSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(
            Yii::$app->request->queryParams,
            Yii::$app->user->identity->level != User::LEVEL_REDACTOR
        );

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param string $id
     * @param string $user_id
     * @param string $category_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NewsWithCategories();

        if ($model->load(Yii::$app->request->post())) {
            // news unverified when posted by redactor
            if (Yii::$app->user->identity->level === User::LEVEL_REDACTOR) {
                $model->status = News::STATUS_NOT_VERIFIED;
            }
            if ($model->user_id == null) {
                $model->user_id = Yii::$app->user->id;
            }
            if ($model->save()) {
                $model->saveCategories();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'categories' => Category::getAvailableCategories(),
            'users' => User::getAllUsers(),
        ]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @param string $user_id
     * @param string $category_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = NewsWithCategories::findOne($id);
        $model->loadCategories();

        if (Yii::$app->user->identity->level == User::LEVEL_REDACTOR) {
            if ($model->status == News::STATUS_VERIFIED) {
                Yii::info(
                    'Access violation (news already accepted): User ['
                    . Yii::$app->user->identity->username . '] at ' . __METHOD__
                    , 'security'
                );
                throw new ForbiddenHttpException('You are not allowed to perform this action');
            }
            if ($model->user_id != Yii::$app->user->id) {
                Yii::info(
                    'Access violation (not author of news): User ['
                    . Yii::$app->user->identity->username . '] at ' . __METHOD__
                    , 'security'
                );
                throw new ForbiddenHttpException('You are not allowed to perform this action');
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->saveCategories();
            Yii::info('[news][update][' . $model->id . '][' . $model->title . ']', 'userBehaviour');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'categories' => Category::getAvailableCategories(),
                'users' => User::getAllUsers()
            ]);
        }
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @param string $user_id
     * @param string $category_id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->user->identity->level == User::LEVEL_REDACTOR) {
            if ($model->status == News::STATUS_VERIFIED) {
                Yii::info(
                    'Access violation (news already accepted): User ['
                    . Yii::$app->user->identity->username . '] at ' . __METHOD__
                    , 'security'
                );
                throw new ForbiddenHttpException('You are not allowed to perform this action');
            }
            if ($model->user_id != Yii::$app->user->id) {
                Yii::info(
                    'Access violation (not author of news): User ['
                    . Yii::$app->user->identity->username . '] at ' . __METHOD__
                    , 'security'
                );
                throw new ForbiddenHttpException('You are not allowed to perform this action');
            }
        }

        Yii::info('[news][delete][' . $model->id . '][' . $model->title . ']', 'userBehaviour');

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @param string $user_id
     * @param string $category_id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\User;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()) {
                Yii::info('Authentication: ok [' . Yii::$app->request->post()['LoginForm']['username'] . ']', 'security');
                return $this->goBack();
            } else {
                Yii::info('Authentication: fail [' . Yii::$app->request->post()['LoginForm']['username'] . ']', 'security');
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        Yii::info('Authentication: logged out', 'security');
        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Event;
use common\models\News;
use common\models\NewsAttach;
use frontend\components\FrontController;
use Yii;
use frontend\models\ContactForm;
use yii\helpers\ArrayHelper;

/**
 * Site controller
 */
class SiteController extends FrontController
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $newsModel = new News();
        $eventModel = new Event();

        // these dont affect global exclude
        $modelsWeekTop = $newsModel->getWeekTop(5);

        // these do, order matters
        $modelsSlider = $newsModel->getSliderNews();
        $modelsUnderSlider = $newsModel->getNewestWithoutDuplicates(4);
        $modelsNextToEvents = $newsModel->getNewestWithoutDuplicates(4);

        return $this->render('index', [
            'slider' => $modelsSlider,
            'underSlider' => $modelsUnderSlider,
            'weekTop' => $modelsWeekTop,
            'nextToEvents' => $modelsNextToEvents,
            'events' => $eventModel->getClosest(),
            'fetchedNewsIds' => $newsModel->fetchedNewsIds,
        ]);
    }

    public function actionMore($fetched, $amount = 6)
    {
        $model = new News();

        $fetchedArray = [];
        foreach (explode(',', $fetched) as $item) {
            $fetchedArray[] = (int)$item;
        }

        $data = [
            'data' => '',
            'fetchedNewsIds' => $fetched,
        ];

        $model->fetchedNewsIds = $fetchedArray;
        $modelsToRender = $model->getNewestWithoutDuplicates($amount);
        if ($modelsToRender != null) {
            $data['data'] = $this->renderPartial('newsRow', [
                'models' => $modelsToRender,
            ]);
        }
        
        $data['fetchedNewsIds'] = $model->fetchedNewsIds;

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        \Yii::$app->response->data = $data;
        \Yii::$app->end();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['contactEmail'])) {
                Yii::$app->session->setFlash('sent', true);
            } else {
                Yii::$app->session->setFlash('sent', false);
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionPrivacyPolicy()
    {
        return $this->render('privacy-policy');
    }

    public function actionOffline()
    {
        echo 'Przerwa techniczna, wracamy za kilka minut';
        exit(0);
    }
}

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title .= 'Kontakt';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <div class="contact-box">
        <div class="padded-multiline">
            <h1 class="gradient-blue-heading">Masz ciekawego newsa lub chcesz się<br>skontaktować? Wypełnij formularz.</h1>
        </div>

        <?php if (Yii::$app->session->hasFlash('sent')): if (Yii::$app->session->hasFlash('sent') == true) : ?>
            <style>p.alert {margin-top: 20px;}</style>
            <p class="alert alert-success">Dziękujemy za kontakt z nami. Odpowiemy tak szybko, jak to możliwe</p>
        <?php elseif (Yii::$app->session->hasFlash('sent') == false) : ?>
            <p class="alert alert-danger">Wysyłanie wiadomości nie powiodło się.</p>
        <?php endif; endif; ?>

        <h2>Wybierz cel kontaktu</h2>
        <input type="checkbox" id="news">
        <label for="news" class="contact-purpose">mam newsa</label>
        <input type="checkbox" id="other">
        <label for="other" class="contact-purpose">inna sprawa</label>

        <h2 style="padding-bottom: 0">Wypełnij formularz</h2>
        <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

            <?= $form->field($model, 'name')->textInput(['autofocus' => true])->input('text', ['placeholder' => 'Imię i nazwisko']) ?>
            <?= $form->field($model, 'email')->input('email', ['placeholder' => 'E-mail']); ?>
            <?= $form->field($model, 'subject')->input('text', ['placeholder' => 'Temat']) ?>
            <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>
            <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className()) ?>

            <div class="form-group">
                <?= Html::submitButton('Wyślij', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>

        <div class="contact-right">
            <div class="address">
                <p class="header" style="text-transform: none; text-align: center; margin: 0; padding: 0;">
                    GameLoad
                </p>
            </div>
            <div class="email">
                <p>
                    Możesz również skontaktować się przez mail:
                </p>
                <p class="email-bigger">
                    kontakt@gameload.pl
                </p>
            </div>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>Przepraszamy, ale coś poszło nie tak. Jeżeli błąd się powtarza, daj nam znać na kontakt@gameload.pl.</p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\web\View;
use frontend\components\NewsTileWidget;

$this->title = Yii::$app->name . ' · Strona główna';
\frontend\assets\SlickAsset::register($this);

$fetchedNewsIdsCommas = implode(',', $fetchedNewsIds);

$js = <<<JS

var fetched = '$fetchedNewsIdsCommas'
var loading = false;

$('.slider').slick({
    'draggable': false,
    'arrows': false,
    'dots': true,
    'appendDots': $('.slider'),
    'autoplay': true,
    'slide': 'div'
});

$('#load-more').click(function () {
    if (loading) {
        return;
    }
    loading = true;
    $('#load-more').addClass('loading');

    $.ajax({
        type: 'get',
        url: '/site/more/' + fetched + '/6',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Accept': 'application/json'
        },
        success: function (r) {
            $('.more-news.row').prepend(r.data);
            fetched = r.fetchedNewsIds;
            console.log(r);
        },
        complete: function () {
            loading = false;
            $('#load-more').removeClass('loading');
        },
    });
});

JS;
$this->registerJs($js, \yii\web\View::POS_READY);

?>

<?php // slider ?>
<div class="row">
    <div class="slider col-xs-12">
        <?php foreach ($slider as $s): ?>
            <div class="news-500 news slide">
                <a class="news-link" href="<?= \yii\helpers\Url::to(['news/view', 'id' => $s->id, 'slug' => $s->slug]) ?>">
                    <div class="under-link-wrap">
                        <div class="news-cats">
                            <?php foreach ($s->categories as $c): ?>

                                <span<?= $c->color != '' ? ' style="color: ' . $c->color . '; border-color: ' . $c->color . ';"' : '' ?>><?= $c->name ?></span>
                            <?php endforeach; ?>
                        </div>
                        <div class="date">
                            <p><?= $s->date; ?></p>
                        </div>
                        <h3 class="title"><?= $s->title ?></h3>
                        <div class="news-img-wrapper"><div class="news-img" style="background-image: url('<?= $s->img ?>')"></div></div>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<?php // section 1 ?>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div class="row">
            <?php foreach ($underSlider as $s) echo NewsTileWidget::widget(['model' => $s]); ?>
        </div>
    </div>
    <div class="col-xs-12 col-md-4 week">
        <h2>Najgorętsze artykuły tygodnia</h2>
        <div class="separator-week"></div>
        <ul>
            <?php foreach ($weekTop as $s): ?>
                <li>
                    <a href="<?= \yii\helpers\Url::to(['news/view', 'id' => $s->id, 'slug' => $s->slug]) ?>">
                        <div class="img" style="background-image: url('<?= $s->img ?>')"></div>
                        <h3><?= $s->title ?></h3>
                        <div class="clearfix"></div>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<?php // section 2 ?>
<div class="row">
    <div class="fb-like-section section-v-gradient-header">
        <a href="https://www.facebook.com/GameLoadPL">
            <div class="gradient">
                <img class="gradient-icon" src="<?= Yii::getAlias('@web/img/fb_icon_white.svg'); ?>">
            </div>
            <div class="padded-multiline">
                <h2>Chcesz być na bieżąco?<br>Polub nas na FB!</h2>
            </div>
        </a>
        <div class="clearfix"></div>
    </div>


    <div class="col-xs-12 col-md-8">
        <div class="row">
            <?php foreach ($nextToEvents as $s) echo NewsTileWidget::widget(['model' => $s]); ?>
        </div>
    </div>
    <div class="col-xs-12 col-md-4 event-wrapper">
        <div class="event-gradient"></div>
        <div class="header">nadchodzące wydarzenia tematyczne</div>
        <div class="row">
            <?php $i = 0; foreach ($events as $s): ?>
            <div class="news col-xs-12 <?= $i == 0 ? 'first' : 'second'; ?>">
                <a class="news-link" href="<?= \yii\helpers\Url::to(['event/view', 'id' => $s->id, 'slug' => $s->slug]) ?>">
                    <div class="under-link-wrap">
                        <div class="date-and-title">
                            <div class="date"><?= $s->date_from ?> <?= ($s->date_to != null) ? ' - ' . $s->date_to : ''; ?></div>
                            <h3 class="title gradient-blue-heading"><?= $s->name ?></h3>
                        </div>
                        <div class="news-img-wrapper"><div class="news-img" style="background-image: url('<?= $s->img ?>')"></div></div>
                    </div>
                </a>
            </div>
            <?php $i++; endforeach; ?>

            <a class="events-more" href="<?= \yii\helpers\Url::to(['event/list']); ?>">Zobacz więcej</a>
        </div>
    </div>
</div>

<div class="more-news row">
    <div class="row" style="margin-top: 20px;">
        <button class="big-button" id="load-more">Załaduj więcej</button>
    </div>
</div>

frontend/views/site/newsRow.php
<?php
use frontend\components\NewsTileWidget;
?>

<div class="col-xs-12">
    <div class="row">
        <?php 
        foreach ($models as $m) echo NewsTileWidget::widget([
            'model' => $m, 
            'colSize' => 4,
        ]); 
        ?>
    </div>
</div>

frontend/views/site/privacy-policy.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'GameLoad · Polityka prywatności';
?>

<div class="padded-multiline">
    <h1 class="gradient-blue-heading">Polityka prywatności</h1>
</div>

<p>&nbsp;</p>
<p>&nbsp;</p>

<p>GameLoad (CFA) szanuje prawo użytkowników do prywatności. Dba, ze szczególną troską, o ochronę ich danych osobowych oraz stosuje odpowiednie rozwiązania technologiczne zapobiegające ingerencji w prywatność użytkowników osób trzecich. Chcielibyśmy, by każdy internauta korzystający z naszych usług i odwiedzający nasze strony czuł się w pełni bezpiecznie, stąd wprowadzone, w niektórych serwisach, systemy rejestracji i logowania. Użytkownik, po zarejestrowaniu się, uzyskuje dostęp komentarzy itp. Rejestracja nie jest obowiązkowa.</p>

<h3>Cookies i inne podobne technologie</h3>

<p>
    Podmiotem zamieszczającym informacje w formie plików cookies (tzw. ciasteczek) i innych podobnych technologii w urządzeniu końcowym Użytkownika (np. komputerze, laptopie, smartfonie, Smart TV) oraz uzyskującym do nich dostęp jest GameLoad (CFA) z siedzibą w Stężycy.
</p>
<p>
    Zamieszczać informacje w urządzeniu końcowym użytkownika i korzystać z nich mogą także podmioty współpracujące z CFA., m.in. partnerzy świadczący usługi analityczne, reklamodawcy, twórcy aplikacji, sieciowe agencje reklamowe.
</p>
<p>
    Pliki cookies stanowią dane informatyczne, w szczególności pliki tekstowe, które przechowywane są w urządzeniu końcowym Użytkownika serwisów i aplikacji CFA. Cookies zazwyczaj zawierają nazwę domeny serwisu internetowego, z którego pochodzą, czas przechowywania ich na urządzeniu końcowym oraz unikalny numer.
</p>
<p>
    Pliki cookies nie służą identyfikacji użytkownika i na ich podstawie nie jest ustalana tożsamość użytkownika.
    Strona internetowa wydawcy (tu: należąca do CFA) może umieścić plik cookie w przeglądarce, jeśli przeglądarka to umożliwia. Co ważne, przeglądarka zezwala stronie internetowej na dostęp jedynie do plików cookies umieszczonych przez tę stronę, a nie do plików umieszczonych przez inne strony internetowe.
</p>


<h3>Dlaczego z tego korzystamy?</h3>

<p>Korzystamy z plików cookies i innych podobnych technologii w celach:</p>
<ul>
    <li>świadczenia usług;</li>
    <li>
        dostosowywania zawartości serwisów i aplikacji do preferencji Użytkownika oraz optymalizacji korzystania ze stron internetowych; np. pliki cookies pozwalają w szczególności rozpoznać urządzenie Użytkownika i odpowiednio wyświetlić stronę internetową dostosowaną do jego indywidualnych potrzeb;
    </li>
    <li>
        tworzenia statystyk, które pomagają zrozumieć, w jaki sposób Użytkownicy korzystają ze serwisów i aplikacji, co umożliwia ulepszanie ich struktury i zawartości;
    </li>
    <li>
        utrzymania sesji Użytkownika (po zalogowaniu), dzięki czemu Użytkownik nie musi na każdej podstronie internetowej danego serwisu i aplikacji ponownie wpisywać loginu i hasła;
    </li>
    <li>
        prezentacji reklam, m.in. w sposób uwzględniający zainteresowania Użytkownika czy jego miejsce zamieszkania (indywidualizowanie przekazu reklamowego) i z gwarancją wyłączenia możliwości wielokrotnego prezentowania Użytkownikowi tej samej reklamy;
    </li>
    <li>
        realizacji ankiet - w szczególności by uniknąć wielokrotnej prezentacji tej samej ankiety temu samemu Odbiorcy oraz by prezentować ankiety w sposób uwzględniający zainteresowania odbiorców.
    </li>
</ul>

<h3>Rodzaje plików cookies, które wykorzystujemy</h3>

<p>
    Z uwagi na czas życia cookies i innych podobnych technologii, stosujemy dwa zasadnicze rodzaje tych plików:
</p>
<ul>
    <li>sesyjne - pliki tymczasowe przechowywane w urządzeniu końcowym Użytkownika do czasu wylogowania, opuszczenia strony internetowej i aplikacji lub wyłączenia oprogramowania (przeglądarki internetowej);</li>
    <li>stałe - przechowywane w urządzeniu końcowym Użytkownika przez czas określony w parametrach plików cookies lub do czasu ich usunięcia przez Użytkownika.</li>
</ul>

<p>Ze względu na cel, jakiemu służą pliki cookies i inne podobne technologie, stosujemy ich następujące rodzaje:</p>
<ul>
    <li>niezbędne do działania usługi i aplikacji- umożliwiające korzystanie z naszych usług, np. uwierzytelniające pliki cookies wykorzystywane do usług wymagających uwierzytelniania;</li>
    <li>pliki służące do zapewnienia bezpieczeństwa, np. wykorzystywane do wykrywania nadużyć w zakresie uwierzytelniania
        wydajnościowe - umożliwiające zbieranie informacji o sposobie korzystania ze stron internetowych i aplikacji;</li>
    <li>funkcjonalne - umożliwiające "zapamiętanie" wybranych przez Użytkownika ustawień i personalizację interfejsu Użytkownika, np. w zakresie wybranego języka lub regionu, z którego pochodzi Użytkownik, rozmiaru czcionki, wyglądu strony internetowej i aplikacji itp.;</li>
    <li>reklamowe - umożliwiające dostarczanie Użytkownikom treści reklamowych bardziej dostosowanych do ich zainteresowań;
        statystyczne - służące do zliczana statystyk dotyczących stron internetowych i aplikacji.</li>
</ul>

<h3>Inne technologie</h3>

<p>Dla zapewnienia wygody użytkowania naszych serwisów używamy technologii Local Storage Object (LSO), zbliżonej zasadą działania do plików cookies, mającej jednak nieco inne właściwości.</p>
<p>LSO to wydzielona część pamięci przeglądarki, służąca do przechowywania danych zapisywanych przez serwisy. Dostęp do niej może uzyskać tylko strona internetowa działający w tej samej witrynie, z której dane zostały zapisane, jednak inaczej niż w przypadku cookies, nie są one wysyłane przez przeglądarkę przy każdym odwołaniu do serwera. Dane w Local Storage Object są długotrwale przechowywane przez przeglądarkę i nie są usuwane po zamknięciu przeglądarki ani nie mają określonego czasu ważności.</p>
<p>Podkreślamy, że używamy tej technologii wyłącznie dla wygody naszych użytkowników i w celu świadczenia im usług na jak najwyższym poziomie.</p>

<h3>Zarządzanie ustawieniami przeglądarki</h3>

<p>W wielu przypadkach oprogramowanie służące do przeglądania stron internetowych (przeglądarka internetowa) domyślnie dopuszcza przechowywanie informacji w formie plików cookies i innych podobnych technologii w urządzeniu końcowym Użytkownika. Użytkownik może jednak w każdym czasie dokonać zmiany tych ustawień. Niedokonanie zmian oznacza, że w/w informacje mogą być zamieszczane i przechowywane w jego urządzeniu końcowym, a tym samym że będziemy przechowywać informacje w urządzeniu końcowym użytkownika i uzyskiwać dostęp do tych informacji.</p>
<p>Z poziomu przeglądarki internetowej, z której Użytkownik korzysta możliwe jest np. samodzielne zarządzanie plikami cookies. W najpopularniejszych przeglądarkach istnieje m.in. możliwość:</p>
<ul>
    <li>
        zaakceptowania obsługi cookies, co pozwala Użytkownikowi na pełne korzystanie z opcji oferowanych przez witryny internetowe;
        zarządzania plikami cookies na poziomie pojedynczych, wybranych przez Użytkownika witryn;
    </li>
    <li>określania ustawień dla różnych typów plików cookie, na przykład akceptowania plików stałych jako sesyjnych itp.;
        blokowania lub usuwania cookies.</li>
</ul>

<h3>Informacje dodatkowe</h3>

<p>Dodatkowe informacje na temat plików cookies i innych technologii można znaleźć m.in. pod adresem wszystkoociasteczkach.pl, youronlinechoices.com lub w sekcji Pomoc w menu przeglądarki internetowej.</p>

<h3>Niepożądane treści</h3>

<p>W serwisach CFA nie ma miejsca na treści, które są sprzeczne z prawem polskim i międzynarodowym, nawołują do nienawiści rasowej, wyznaniowej czy etnicznej. Nie ma tu pornografii, materiałów nagannych moralnie, treści uważanych powszechnie za nieetyczne czy obelżywe.</p>